image: Visual Studio 2017

environment:
  PYTHON: "C:\\Miniconda"
  matrix:
    - CONDA_BUILD_PY: 3.5
    - CONDA_BUILD_PY: 3.6
    - CONDA_BUILD_PY: 3.7

install:
  - "choco install miniconda3 --params=\"'/D:%PYTHON%'\""
  - "SET PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%"
  - "python --version"
  - "python -c \"import struct; print(struct.calcsize('P') * 8)\""

  - "conda config --set always_yes yes --set changeps1 no"
  - "conda config --set anaconda_upload no"
  - "conda update -q --all"
  - "conda update -q conda"
  - "conda info -a"
  - "conda install -q conda-build conda-verify anaconda-client"

build_script:
  - "SET MPLBACKEND=agg"
  - "python --version"
