image: Visual Studio 2017

environment:
  MINICONDA: "C:\\Miniconda3-x64"
  matrix:
    - CONDA_BUILD_PY: 3.5
    - CONDA_BUILD_PY: 3.6
    - CONDA_BUILD_PY: 3.7

install:
  - ps: "$env:path = \"$env:MINICONDA;$env:MINICONDA\\Scripts;$env:path\""
  - ps: "conda config --set always_yes yes --set changeps1 no"
  - ps: "conda config --set anaconda_upload no"
  - ps: "conda update -q --all"
  - ps: "conda update -q conda"
  - ps: "conda info -a"

build_script:
  - "SET MPLBACKEND=agg"
  - "python --version"
